name: Release Docker Image

on:
  release:
    types: [created]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/BKRCalculatorApi:latest -t docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}/BKRCalculatorApi:v${{ github.event.release.tag_name }} -f BKRCalculator/Dockerfile .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push docker.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/BKRCalculatorApi:latest
          docker push docker.pkg.github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/BKRCalculatorApi:v${{ github.event.release.tag_name }}
